[tool.poetry]
name = "hexlet-code"
version = "0.1.0"
description = "The educational project of the course \"Python developer\" of the Hexlet programming school"
authors = ["Konstantin Pavlov <k.pavlov.reg@yandex.ru>"]
readme = "README.md"
packages = [{include = "task_manager"}]


[tool.poetry.dependencies]
python = "^3.10"
django = "^4.2.6"
gunicorn = "^21.2.0"
django-bootstrap5 = "^23.3"
python-dotenv = "^1.0.0"
django-filter = "^23.5"
django-extensions = "^3.2.3"
dj-database-url = "^2.1.0"
psycopg2-binary = "^2.9.9"
rollbar = "^0.16.2"
whitenoise = {extras = ["brotli"], version = "^6.7.0"}
uvicorn = "^0.30.3"


[tool.poetry.group.dev.dependencies]
django-shell-plus = "^1.1.7"
ipython = "^8.21.0"
flake8 = "^7.0.0"
coverage = "^7.4.4"
black = "^24.3.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
