# Generated by Django 4.2.6 on 2024-01-11 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_created_at_user_updated_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
